name: deploy-to-ec2
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Assert secrets exist
        run: |
          [ -n "${{ secrets.EC2_HOST }}" ] || { echo "EC2_HOST is EMPTY"; exit 1; }
          [ -n "${{ secrets.EC2_USER }}" ] || { echo "EC2_USER is EMPTY"; exit 1; }
          [ -n "${{ secrets.EC2_SSH_KEY }}" ] || { echo "EC2_SSH_KEY is EMPTY"; exit 1; }

      - name: Check TCP 22 reachability
        run: |
          sudo apt-get update >/dev/null
          sudo apt-get install -y netcat-openbsd >/dev/null
          nc -zv ${{ secrets.EC2_HOST }} 22 || true

      - name: Add EC2 to known_hosts (tolerant)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 -T 5 -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true

      - name: Upload via rsync (native)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rsync openssh-client
      
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
          # 可选：写入 known_hosts（不想写可用 -o StrictHostKeyChecking=no）
          ssh-keyscan -p 22 -T 5 -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true
      
          # 先探一次 SSH，确保能通
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'ssh ok'"
      
          # 真正同步（排除 .git/README.md）
          rsync -avzr --delete --exclude '.git' --exclude 'README.md' \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 22" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/site/


      - name: Publish & reload nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rsync -av --delete --exclude '.git' --exclude 'README.md' \
              /home/ec2-user/site/ /usr/share/nginx/html/
            sudo find /usr/share/nginx/html -type d -exec chmod 755 {} \;
            sudo find /usr/share/nginx/html -type f -exec chmod 644 {} \;
            sudo restorecon -Rv /usr/share/nginx/html || true
            sudo nginx -t && sudo systemctl reload nginx
