name: deploy-to-ec2
on:
  push:
    branches: [ main ]
    paths:
      - "index.html"
      - "css/**"
      - "img/**"
      - "js/**"
      - "!README.md"

permissions:
  contents: read

concurrency:
  group: ec2-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync files to EC2
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude '.git' --exclude 'README.md'
          path: .
          remote_path: /home/ec2-user/site/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}

      - name: Publish & reload nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rsync -av --delete --exclude '.git' --exclude 'README.md' \
              /home/ec2-user/site/ /usr/share/nginx/html/
            sudo find /usr/share/nginx/html -type d -exec chmod 755 {} \;
            sudo find /usr/share/nginx/html -type f -exec chmod 644 {} \;
            sudo restorecon -Rv /usr/share/nginx/html || true
            sudo nginx -t && sudo systemctl reload nginx
